[package]
name = "cepack"
version = "0.1.0"
authors = ["jan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pelite = "0.7.1"
inflate = "*"
quick-error = "1.2.2"